### ISSUE TITLE
30 multiple choice questions about a good anime

### ISSUE THREAD

**Issue by MatthewCaseres** [MatthewCaseres/actuarialopensource.org#17]
YAML is probably the format for storage. Then we can parse into a variety of formats. 

Something like this will work.

```
question:
  text: "Who is the main character of the anime series 'Death Note'?"
  type: "multipleChoice"
  options:
    - "Ichigo Kurosaki"
    - "Naruto Uzumaki"
    - "Light Yagami"
    - "Monkey D. Luffy"
  answer:
    correct: 2
    explanation: "Light Yagami is the main character in the 'Death Note' anime series. He comes into possession of the Death Note and becomes a vigilante known as 'Kira'."
```

That question probably isn't good. We want questions that are specific and should be challenging even for fans of the anime. Pick an anime and write 50 good questions.
